version: '3'
services:

  app-django:
    build:
      context: django
      dockerfile: Dockerfile
    container_name: app-django
    ports:
      - "8000:8000"
    restart: unless-stopped
    tty: true
    environment:
      VERIFICATION_TOKEN: ${VERIFICATION_TOKEN}
      BOT_USER_ACCESS_TOKEN: ${BOT_USER_ACCESS_TOKEN}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: us-east-1
    volumes:
      - ./django/avanan:/opt/app/avanan
    networks:
      - app-network

  db-mysql:
    restart: always
    image: mysql:5.7
    container_name: db-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "strong_root_password"
    command: --init-file /data/application/init.sql
    volumes:
      - ./mysql:/var/lib/mysql
      - ./django/avanan/init.sql:/data/application/init.sql
    networks:
      - app-network

  app-dlp:
    build:
      context: dlp
      dockerfile: Dockerfile
    container_name: app-dlp
    ports:
      - "8001:8001"
    restart: unless-stopped
    tty: true
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: us-east-1
    volumes:
      - ./dlp/dlp:/opt/app/dlp
    networks:
      - app-network


networks:
  app-network:
    driver: bridge