# Generated by Django 3.1.6 on 2021-02-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
